### ISSUE TITLE
Finding Research Papers

### ISSUE THREAD

**Issue by satyam04sharma** [satyam04sharma/CECS-550---Survey-Paper#1]
## Search topics that are -

- Not very old
- Present in Major libraries like IEEE, ACM, AAAI , etc.
- Are related to topics
     - Bayesian Decision Theory
     - Max Likelihood and Bayesian Parameter Estimation
     - Nonparametric Techniques 
     - Linear Discriminant

**Comment by JoeyChor** [comment]
Robust and Sparse Linear Discriminant Analysis via an Alternating Direction Method of Multipliers

In this paper, we propose a robust linear discriminant analysis (RLDA) through Bhattacharyya error bound optimization. RLDA considers a nonconvex problem with the L 1 -norm operation that makes it less sensitive to outliers and noise than the L 2 -norm linear discriminant analysis (LDA). In addition, we extend our RLDA to a sparse model (RSLDA). Both RLDA and RSLDA can extract unbounded numbers of features and avoid the small sample size (SSS) problem, and an alternating direction method of multipliers (ADMM) is used to cope with the nonconvexity in the proposed formulations. Compared with the traditional LDA, our RLDA and RSLDA are more robust to outliers and noise, and RSLDA can obtain sparse discriminant directions. These findings are supported by experiments on artificial data sets as well as human face databases.

https://ieeexplore.ieee.org/abstract/document/8710607

**Comment by JoeyChor** [comment]
Here's how we can section this:
* Background of paper (what has been done/tried, what is current norm)
* Problems we want to solve (Number of features, small sample size problem)
* Introduction of paper and inspiration of why we chose this paper
* Key contributions of paper: Description of RLDA/RSLDA and how they work
* Results of contribution: how does RLDA/RSLDA perform (include analysis of results)
* Any concluding remarks

To do: Figure where ADMM fits

**Comment by Ishan511** [comment]
The paper proposes a robust and sparse variant of Linear Discriminant Analysis (LDA) that can handle outliers and high-dimensional data with sparse feature sets and also uses an Alternating Direction Method of Multipliers (ADMM) algorithm to solve the optimization problem. The proposed method has several potential advantages over traditional LDA approaches. So I think it would be a good choice.

**Comment by aniruddhagawande** [comment]
Thanks for the suggestion, @JoeyChor! I agree that this paper covers the requested topics and looks promising. I'm in favor of choosing this paper.

**Comment by jajooabhishek** [comment]
I agree that "Robust and Sparse Linear Discriminant Analysis via an Alternating Direction Method of Multipliers" provides valuable contributions to the field of linear discriminant analysis. RLDA and RSLDA are more robust to outliers and noise than traditional LDA due to the use of L1-norm and ADMM to cope with nonconvexity. The paper's recent publication and presence in major libraries demonstrate its relevance and impact.

**Comment by satyam04sharma** [comment]
### Everyone agreed to PCA paper
`Robust and Sparse Linear Discriminant Analysis via an Alternating Direction Method of Multipliers`
~from IEEE~
